### ISSUE TITLE
Suggestion: Default location

### ISSUE THREAD

**Issue by troystaylor** [AKA-Enterprise-Solutions/SafeWorkplace-ContactTracing#10]
Allow admin to set default location or have user select default location on first launch. As most of our users are at one of our three locations, I'm going to have the app default to one location using an added new variable, but it would be great if the user could select this.

**Comment by Danish-AKA** [comment]
@troystaylor The app currently handles that but in a different way. If a user logs in for the first time and check-in toa zone, the location of that zone is now made default when the user logs in again. We always use the most recently used location to default the filter on the app. Hope that clarifies your question.

**Comment by troystaylor** [comment]
That makes sense (to me) and will be a key point for our training. In our case, it opens to multiple desk options (one for each office), which has confused other testers.

![brave_8vUrXK4OuB](https://user-images.githubusercontent.com/44444967/85294006-1e893e80-b46c-11ea-9779-0f38ecc9fe77.png)

**Comment by Danish-AKA** [comment]
Got it. I think adding location in the card structure would be useful. I'll discuss it with the team and see if we can add that to the card - making selection of zone easier if no filter is used. Thanks.

**Comment by Danish-AKA** [comment]
Fixed in latest release v2020.7.27.2
