### ISSUE TITLE
Suggestion: Optional step to change email notification time

### ISSUE THREAD

**Issue by troystaylor** [AKA-Enterprise-Solutions/SafeWorkplace-ContactTracing#11]
Add optional change to Step 9.7 - Flow can be modify to adjust timing of automated email. Our situation would allow users to stay signed in to their desk all day for reporting purposes. So the first delay could be changed to 540 minutes with a 30 minute additional delay for reporting. An admin might also only want to record meeting or break rooms, so they could change it to a 30-60 minute first delay with automatic 15 minute reporting delay. Or they might want to completely turn this off and require users to sign out every time to get a true minute to minute record.

![brave_BVSyGOWM8H](https://user-images.githubusercontent.com/44444967/85411629-9459dc80-b536-11ea-8eed-fb36d3b42013.png)

**Comment by Danish-AKA** [comment]
Documentation updated
