### ISSUE TITLE
Same day generate report don't show all eligible records

### ISSUE THREAD

**Issue by Danish-AKA** [AKA-Enterprise-Solutions/SafeWorkplace-ContactTracing#4]
**Describe the bug**
When the Tracer Contact is of type Employee it does not show overlapping Guest contacts for Contact Tracing report.

**To Reproduce**
1. Using the canvas app check-in to "Zone A" for Employee X
2. Using model-driven app create presence record for Guest Y in Zone A
3. Make sure both have same entry and exit date
4. Generate report for Employee X

**Expected behavior**
Guest Y should show as traced contact

**Comment by Adramca** [comment]
Issue has been resolved

**Comment by Danish-AKA** [comment]
Fixed in latest release v2020.7.27.2
