### ISSUE TITLE
Unable to assign security role to tenant following instructions

### ISSUE THREAD

**Issue by troystaylor** [AKA-Enterprise-Solutions/SafeWorkplace-ContactTracing#5]
For Step 6, when I created the environment, I added all tenant users. When I go to share the app with everyone, I see the greyed out dropdowns for Assign a security role with the detail Cannot assign roles to a tenant.
![brave_56fOJ4Q48x](https://user-images.githubusercontent.com/44444967/85171458-0da6b600-b23d-11ea-92e0-11f3cc7698ea.png)

**Comment by Adramca** [comment]
Thanks Troy. We will update the Readme File. Thanks for pointing this out. Security roles can be setup for individual users or groups, but not for the tenant.

**Comment by Danish-AKA** [comment]
Documentation updated
