### ISSUE TITLE
Suggestion: Literally anyone else for icon

### ISSUE THREAD

**Issue by troystaylor** [AKA-Enterprise-Solutions/SafeWorkplace-ContactTracing#7]
Please consider packaging a different icon for the user app. No one today wants to look at another white man when opening the PowerApp. A quick Google search has many timely results, maybe:
https://publicdomainvectors.org/en/free-clipart/Man-in-a-mask/80691.html
https://pixabay.com/illustrations/coronavirus-virus-mask-quarantine-5123202/

**Comment by Adramca** [comment]
Thanks for the feedback and the suggestions. We'll look into those and other options!
