### ISSUE TITLE
Unable to update Zone

### ISSUE THREAD

**Issue by troystaylor** [AKA-Enterprise-Solutions/SafeWorkplace-ContactTracing#8]
Started creating zones and realized I had only been filling required name and location. Went back to zone to add exposure level and now receiving Business Process Error when saving:

Business Process Error
A record alredy exists for the same Combination of Zone Name/Location. Please update existing record or change values in current record.
(already is spelled incorrectly in error)

![brave_iUviPbVOnL](https://user-images.githubusercontent.com/44444967/85208007-03e38800-b2fb-11ea-890e-240874bae229.png)
![brave_y4mhspmUv0](https://user-images.githubusercontent.com/44444967/85208008-080fa580-b2fb-11ea-8a49-0c2ad4702f39.png)

**Comment by Danish-AKA** [comment]
Fixed in latest release v2020.7.27.2
