### ISSUE TITLE
Zone name cannot include apostrophe

### ISSUE THREAD

**Issue by troystaylor** [AKA-Enterprise-Solutions/SafeWorkplace-ContactTracing#9]
Unable to save new zone or update existing zone name that includes apostrophe

![brave_ScVuNjnTM6](https://user-images.githubusercontent.com/44444967/85208174-49548500-b2fc-11ea-88be-184b0ee3cb6a.png)

**Comment by Danish-AKA** [comment]
Fixed in latest release v2020.7.27.2
